name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup go
      uses: actions/setup-go@v2.1.5
      with:
        go-version: '1.12'
    - run: go mod download
    - run: go test -v ./...